#!/bin/sh

# Debug: Print environment variables (remove in production)
echo "DB_TYPE: $DB_TYPE"
echo "DB_POSTGRESDB_HOST: $DB_POSTGRESDB_HOST"
echo "DB_POSTGRESDB_DATABASE: $DB_POSTGRESDB_DATABASE"
echo "DB_POSTGRESDB_USER: $DB_POSTGRESDB_USER"
echo "DB_POSTGRESDB_PORT: $DB_POSTGRESDB_PORT"

# Export for n8n
export DB_TYPE=postgresdb
export DB_POSTGRESDB_HOST="${DB_POSTGRESDB_HOST}"
export DB_POSTGRESDB_PORT="${DB_POSTGRESDB_PORT}"
export DB_POSTGRESDB_DATABASE="${DB_POSTGRESDB_DATABASE}"
export DB_POSTGRESDB_USER="${DB_POSTGRESDB_USER}"
export DB_POSTGRESDB_PASSWORD="${DB_POSTGRESDB_PASSWORD}"
export DB_POSTGRESDB_SSL_MODE=require

# Start n8n
exec n8n